### ISSUE TITLE
ImportError: cannot import name 'DetrFeatureExtractor' from 'transformers' (unknown location)

### ISSUE THREAD

**Issue by 834799106** [qanastek/HugsVision#17]
HugsVision/hugsvision/inference/SemanticSegmentationInference.py in <module>
      4 
      5 import torch
----> 6 from transformers import DetrFeatureExtractor, DetrForObjectDetection, pipeline
      7 
      8 import numpy as np

ImportError: cannot import name 'DetrFeatureExtractor' from 'transformers' (unknown location)

**Comment by qanastek** [comment]
SemanticSegmentationInference isn't finished yet.

We already have a issue for it #10

**Comment by qanastek** [comment]
Removed from source in faeb3d3
And added to corresponding dev branch in 8cc0826
