### ISSUE TITLE
resume from checkpoint when calling `trainer.train()`

### ISSUE THREAD

**Issue by ohjho** [qanastek/HugsVision#39]
any plans to expose this to `VisionClassifierTrainer` so one can resume training from last checkpoint?

**Comment by qanastek** [comment]
Hello,

Can you make a pull request with the implementation of it ? It’s will be awesome!

**Comment by qanastek** [comment]
Added with a string parameter in the last commit [fa59fd2](https://github.com/qanastek/HugsVision/commit/fa59fd231a476172c539a7d708ebbe3b6edea710)
