### ISSUE TITLE
tuple object has no attribute 'keys'

### ISSUE THREAD

**Issue by M-Melodious** [qanastek/HugsVision#41]
I've been trying to finetune the vision transformer on custom dataset. I followed the steps from one of the tutorial notebook and ran into the following error:
`AttributeError: tuple object has no attribute 'keys'`

I thought I did something wrong so, I decided to try the demo tutorial. But the same error shows up. It seems like a bug. Please see the attached screenshot.
<img width="715" alt="Screenshot 2022-05-13 194032" src="https://user-images.githubusercontent.com/59175105/168304796-34bbfa19-11b4-4681-81c5-5c9001314d3f.png">

**Comment by qanastek** [comment]
Hi,

What version are you using ? Use `pip show HugsVision` and put here the output.

**Comment by M-Melodious** [comment]
Hi there.

Sorry I forgot to mention the version. Here's the screenshot
<img width="868" alt="Screenshot 2022-05-13 201006" src="https://user-images.githubusercontent.com/59175105/168308535-d747d402-ebbf-4c2b-884e-3054fd149eb9.png">

**Comment by guneetsk99** [comment]
![image](https://user-images.githubusercontent.com/43180442/168317549-fbc719e6-d343-49a6-82c1-058c8c740b36.png)
I am suffering from same error

**Comment by qanastek** [comment]
I tried from a new environment :

```bash
conda create -y --name issue_41 python=3.6
conda activate issue_41
pip install hugsvision
cd "./binary_classification/"
pip install -r requirements.txt
pip install pandas
pip install seaborn
```

The code :

```python
import argparse

from hugsvision.dataio.VisionDataset import VisionDataset
from hugsvision.nnet.VisionClassifierTrainer import VisionClassifierTrainer

from transformers import ViTFeatureExtractor, ViTForImageClassification

import pandas as pd
import seaborn as sn
from sklearn.metrics import confusion_matrix

import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt

parser = argparse.ArgumentParser(description='Image classifier')
parser.add_argument('--name', type=str, default="MyVitModel", help='The name of the model')
parser.add_argument('--imgs', type=str, default="/mnt/d/Projects/Datasets/IMAGE/Pneumothorax Binary Classification task/data/", help='The directory of the input images')
parser.add_argument('--output', type=str, default="./out/", help='The output directory of the model')
parser.add_argument('--epochs', type=int, default=1, help='Number of Epochs')
args = parser.parse_args() 

# Load the dataset
train, test, id2label, label2id = VisionDataset.fromImageFolder(
	args.imgs,
	test_ratio   = 0.15,
	balanced     = False,
	augmentation = False,
)

huggingface_model = 'google/vit-base-patch16-224-in21k'

# Train the model
trainer = VisionClassifierTrainer(
	model_name   = args.name,
	train      	 = train,
	test      	 = test,
	output_dir   = args.output,
	max_epochs   = args.epochs,
	cores 	     = 4,
	batch_size   = 12,
	model = ViTForImageClassification.from_pretrained(
	    huggingface_model,
	    num_labels = len(label2id),
	    label2id   = label2id,
	    id2label   = id2label,
	),
	feature_extractor = ViTFeatureExtractor.from_pretrained(
		huggingface_model,
	),
)

ref, hyp = trainer.evaluate_f1_score()

cm = confusion_matrix(ref, hyp)
labels = list(label2id.keys())
df_cm = pd.DataFrame(cm, index = labels, columns = labels)
plt.figure(figsize = (10,7))
sn.heatmap(df_cm, annot=True, annot_kws={"size": 8}, fmt="")
plt.savefig("./imgs/" + str(args.name) + "_conf_matrix_" + str(args.epochs) + ".jpg", bbox_inches = 'tight')
```

It's work perfectly :

![image](https://user-images.githubusercontent.com/19389475/168334921-6293c719-c028-4049-aa51-00a83cc72b23.png)

My env :

```plain
hugsvision - Version: 0.75.3
transformers - Version: 4.18.0
```

**Comment by qanastek** [comment]
Do you have your environment created with Python 3.6 ?

**Comment by guneetsk99** [comment]
I was working with 3.7 
Plus this error didnt occur till yesterday 
As soon as I tried it again this happened

**Comment by guneetsk99** [comment]
I am working on Colab

**Comment by qanastek** [comment]
I tried to force the `4.19.0` but my environment doesn't want to do it. Can you try `transformers==4.18.0` like you mention it ?

**Comment by guneetsk99** [comment]
Should I mention it in requirements because if I do **pip install hugsvision** it causes transformers to download 4.19.0

**Comment by qanastek** [comment]
It's seem to be caused to python 3.7.

**Comment by qanastek** [comment]
I can try a python 3.7 setup locally.

**Comment by guneetsk99** [comment]
Ok sure actually I panicked today (heheh) because the code was running smoothly till yesterday and then suddenly this happened

**Comment by qanastek** [comment]
My py3.7 setup give me the following dependecies :

```plain
hugsvision - Version: 0.75.3
transformers - Version: 4.19.0
Python 3.7.13
```

And it crashed :

![image](https://user-images.githubusercontent.com/19389475/168340665-ef7e94d1-a87b-4903-8bd4-325d830ad803.png)

**Comment by guneetsk99** [comment]
Got it Then I would change the environment and get it running thank you so so much for helping me out your library is a real boon

**Comment by qanastek** [comment]
Thank you very much for your support!
